version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/src/Ml.Cli.WebApp'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build(npm): '
  - package-ecosystem: 'nuget'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/src'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build(nuget): '