version: '3.7'

services:
  ml-cli:
    build:
      context: .
      dockerfile: ./Dockerfile
    #image: dvaew1afahubacr02.azurecr.io/project/mcma/mcma_big_data_et_innovation/receiver:local
    ports:
      - 5000:5000
    depends_on:
      - ml-cli-demo
  ml-cli-demo:
    build:
      context: ./src/Ml.Cli.DemoApi
      dockerfile: ./Dockerfile
    #image: dvaew1afahubacr02.azurecr.io/project/mcma/mcma_big_data_et_innovation/receiver:local
    ports:
      - 6001:6001