version: "3.4"

services:
  database:
    build: ./docker
    #container_name: "ecotag_db"
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
  blob:
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports:
      - 10000:10000
      - 10010:10001
  ecotag:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - 5010:5010
    depends_on:
      - blob
      - database