version: '3.7'

services:
  ml-cli:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - ml-cli-demo
  ml-cli-demo:
    build:
      context: ./src/Ml.Cli.DemoApi
      dockerfile: ./Dockerfile
    ports:
      - 6001:6001