name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    environment: ml-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: npm install
        run: npm install
        working-directory: ./src/Ml.Cli.WebApp/ClientApp

      - name: npm test
        run: npm test -- --runInBand --coverage --watchAll=false
        working-directory: ./src/Ml.Cli.WebApp/ClientApp
        
      - name: npm run build-storybook
        run: npm run build-storybook
        working-directory: ./src/Ml.Cli.WebApp/ClientApp

      - uses: actions/setup-dotnet@v1
  #${{ needs.tags.outputs.new_version }}
      #- run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./coverage/opencover.xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=axaguildev
            -Dsonar.projectKey=AxaGuilDEv_ml-cli
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=**/*.spec.js,**/*.stories.js,**/ClientApp/src/Toolkit/**,**/ClientApp/coverage/**,Scripts/**,**/*.scss,**/__snapshots__/**,**/*[Tt]ests.cs,**/node_modules/**,**/ClientApp/build/**,**/ClientApp/.storybook/**,**/ClientApp/storybook-static/**,**/obj/**,**/__mocks__/**,**/ClientApp/src/serviceWorker.ts
            -Dsonar.javascript.lcov.reportPaths=ClientApp/coverage/lcov.info
            -Dsonar.cs.opencover.reportsPaths=**/opencover.xml

  tags:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag.outputs.new_version }}
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        id: tag_version
        #    if: github.ref == 'refs/heads/master'
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
      - name: Add tag to output step
        id: tag
        #   if: github.ref == 'refs/heads/master'
        run: echo "::set-output name=new_version::${{ steps.tag_version.outputs.new_version }}"
      - name: Add changelog to output step
        id: changelog
        #   if: github.ref == 'refs/heads/master'
        run: echo "::set-output name=changelog::${{ steps.tag_version.outputs.changelog }}"
  release:
    environment: ml-cli
    runs-on: ubuntu-latest
    needs: tags 
    steps:
      - run: dotnet publish ./src/Ml.Cli.WebApp/Ml.Cli.WebApp.csproj -c Release -r linux-x64 --self-contained=true /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:AssemblyVersion=${{ needs.tags.outputs.new_version }} --output ./drop/linux-x64/ml-cli 
      - run: dotnet publish ./src/Ml.Cli.DemoApi/Ml.Cli.DemoApi.csproj -c Release -r linux-x64 --self-contained=true /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:AssemblyVersion=${{ needs.tags.outputs.new_version }} --output ./drop/linux-x64/demo-api
      - run: dotnet publish ./src/Ml.Cli.WebApp/Ml.Cli.WebApp.csproj -c Release -r win-x64 --self-contained=true /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:AssemblyVersion=${{ needs.tags.outputs.new_version }} --output ./drop/win-x64/ml-cli
      - run: dotnet publish ./src/Ml.Cli.DemoApi/Ml.Cli.DemoApi.csproj -c Release -r win-x64 --self-contained=true /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:AssemblyVersion=${{ needs.tags.outputs.new_version }} --output ./drop/win-x64/demo-api
      - run: dotnet publish ./src/Ml.Cli.WebApp/Ml.Cli.WebApp.csproj -c Release -r rhel-x64 --self-contained=true /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:AssemblyVersion=${{ needs.tags.outputs.new_version }} --output ./drop/rhel-x64/ml-cli
      - run: dotnet publish ./src/Ml.Cli.DemoApi/Ml.Cli.DemoApi.csproj -c Release -r rhel-x64 --self-contained=true /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:AssemblyVersion=${{ needs.tags.outputs.new_version }} --output ./drop/rhel-x64/demo-api
      - run: dotnet publish ./src/Ml.Cli.WebApp/Ml.Cli.WebApp.csproj -c Release -r osx-x64 --self-contained=true /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:AssemblyVersion=${{ needs.tags.outputs.new_version }} --output ./drop/osx-x64/ml-cli
      - run: dotnet publish ./src/Ml.Cli.DemoApi/Ml.Cli.DemoApi.csproj -c Release -r osx-x64 --self-contained=true /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:AssemblyVersion=${{ needs.tags.outputs.new_version }} --output ./drop/osx-x64/demo-api

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: linux-x64-ml-cli.zip 
          path: .
          directory: ./drop/linux-x64/ml-cli

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: linux-x64-demo-api.zip
          path: .
          directory: ./drop/linux-x64/demo-api

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: win-x64-ml-cli.zip
          path: .
          directory: ./drop/win-x64/ml-cli
          
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: win-x64-demo-api.zip
          path: .
          directory: ./drop/win-x64/demo-api
          
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: rhel-x64-ml-cli.zip
          path: .
          directory: ./drop/rhel-x64/ml-cli
          
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: rhel-x64-demo-api.zip
          path: .
          directory: ./drop/rhel-x64/demo-api
          
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: osx-x64-ml-cli.zip
          path: .
          directory: ./drop/osx-x64/ml-cli
          
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: osx-x64-demo-api.zip
          path: .
          directory: ./drop/osx-x64/demo-api

      #      - name: Upload linux-x64-ml-cli-webapp Build Artifact
#        uses: actions/upload-artifact@v2
#        with:
#            name: linux-x64-ml-cli-webapp
#            path: ./ubuntu/ml-cli-webapp

      - name: release
        uses: actions/create-release@v1
        #if: ${{ github.ref == 'refs/heads/master' }}
        id: create_release
        with:
          draft: false
          prerelease: false
          body: |
            ${{ needs.tags.outputs.changelog }}
          release_name: "v${{ needs.tags.outputs.new_version }}"
          tag_name: "v${{ needs.tags.outputs.new_version }}"
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./drop/linux-x64/ml-cli/linux-x64-ml-cli.zip
          asset_name: linux-x64-ml-cli.zip
          asset_content_type: application/zip
          
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./drop/win-x64/ml-cli/win-x64-ml-cli.zip
          asset_name: win-x64-ml-cli.zip
          asset_content_type: application/zip
          
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./drop/rhel-x64/ml-cli/win-x64-ml-cli.zip
          asset_name: rhel-x64-ml-cli.zip
          asset_content_type: application/zip
          
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./drop/osx-x64/ml-cli/win-x64-ml-cli.zip
          asset_name: osx-x64-ml-cli.zip
          asset_content_type: application/zip 