name: test release ecotag

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/setup-dotnet@v1
      - run: dotnet publish ./src/Ml.Cli.WebApp/Ml.Cli.WebApp.csproj -c Release -r win-x64 --self-contained=true /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true --output ./drop/win-x64/ml-cli
      - name: LibreOffice install Windows x64
        run: |
          git clone https://github.com/guillaume-chervet/LibreOfficePortal_7.4.2_winx64.git --depth 1 LibreOffice
          mv LibreOffice drop/win-x64/ml-cli
          ls ./drop/win-x64/ml-cli/
          echo "---------------"
          cd drop/win-x64/ml-cli
          rm appsettings-server.Production.json
          cp appsettings-server.DesktopWinx64.json appsettings-server.Production.json 
          cd ClientApp/build-server
          rm environment.json
          cp environment.desktop.json environment.json
      - name: Upload WebApp1 Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Publish win-x64 Fibonacci
          path: ./drop/win-x64/ml-cli
